import { NextRequest, NextResponse } from "next/server";
import { adjustStock, StockMovementType } from "@/lib/stockService";

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const body = await req.json();
    const { quantityChange, type, notes } = body;

    const qty = Number(quantityChange);
    if (isNaN(qty) || qty === 0) {
      return NextResponse.json({ success: false, error: "Valid non-zero quantity change is required" }, { status: 400 });
    }

    if (type === "SALE") {
      return NextResponse.json(
        { success: false, error: "Sales movements can only be generated by issuing bills." },
        { status: 400 }
      );
    }

    const validTypes: StockMovementType[] = ["PURCHASE", "ADJUSTMENT", "DAMAGE", "RETURN"];
    if (!validTypes.includes(type)) {
      return NextResponse.json(
        { success: false, error: `Invalid movement type. Allowed: ${validTypes.join(", ")}` },
        { status: 400 }
      );
    }

    const result = await adjustStock({
      productId: params.id,
      quantityChange: qty,
      type,
      notes: notes || `Manual ${type}`,
      isBilling: false,
    });

    return NextResponse.json({ success: true, data: result });
  } catch (error: any) {
    console.error("POST Adjust Stock Error:", error);
    const status = error.message?.includes("Insufficient stock") || error.message?.includes("Services do not track")
      ? 400
      : 500;
    return NextResponse.json({ success: false, error: error.message }, { status });
  }
}
