import prisma from "./prisma";
import { generateSku } from "./sequence";
import { getProductRollingWACPaise } from "./costService";
import { roundMoney, safeMultiplyQuantityByPaise } from "./money";


export type StockMovementType =
  | "OPENING"
  | "PURCHASE"
  | "SALE"
  | "ADJUSTMENT"
  | "DAMAGE"
  | "RETURN"
  | "RESERVATION"
  | "RELEASE";

export interface CreateProductInput {
  name: string;
  category?: string;
  basePrice?: number | null;
  pricingMode?: string;
  taxRate?: number;
  type?: "PHYSICAL_PRODUCT" | "SERVICE";
  status?: string;
  initialStock?: number;
  minStock?: number;
  description?: string;
  sourceType?: string;
  sourceUrl?: string;
  sourceSlug?: string;
  sourceProductName?: string;
  configurationNotes?: string;
}

export interface AdjustStockInput {
  productId: string;
  quantityChange: number; // positive or negative
  type: StockMovementType;
  notes?: string;
  userId?: string;
  isBilling?: boolean;
}

/**
 * Creates a new product with deterministic auto-generated SKU and records OPENING stock entry if initialStock > 0.
 */
export async function createProductWithStock(input: CreateProductInput, userId?: string) {
  const category = input.category || "General";
  const productType = input.type || "PHYSICAL_PRODUCT";
  const sku = await generateSku(category);
  const initialStock = productType === "PHYSICAL_PRODUCT" ? Math.max(0, Number(input.initialStock) || 0) : 0;
  const pricingMode = input.pricingMode || (input.basePrice !== undefined && input.basePrice !== null ? "FIXED" : "REQUIREMENT_BASED");

  // Import normalizeProductName
  const normalizedName = input.name
    .trim()
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\w\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  const product = await prisma.product.create({
    data: {
      sku,
      name: input.name.trim(),
      normalizedName,
      category,
      description: input.description?.trim() || null,
      type: productType,
      pricingMode,
      status: input.status || "ACTIVE",
      basePrice: input.basePrice !== undefined && input.basePrice !== null ? Number(input.basePrice) : null,
      taxRate: Number(input.taxRate) || 18,
      stockQuantity: initialStock,
      minStock: Number(input.minStock) || 5,
      sourceType: input.sourceType || "MANUAL",
      sourceUrl: input.sourceUrl || null,
      sourceSlug: input.sourceSlug || null,
      sourceProductName: input.sourceProductName || null,
      configurationNotes: input.configurationNotes?.trim() || null,
    },
  });

  // Lock 3: Record explicit OPENING stock ledger movement if physical and stock > 0
  if (productType === "PHYSICAL_PRODUCT" && initialStock > 0) {
    await prisma.stockLedgerEntry.create({
      data: {
        productId: product.id,
        quantitySigned: initialStock,
        type: "OPENING",
        referenceType: "OPENING_BALANCE",
        referenceId: product.id,
        notes: input.sourceType === "WEBSITE" 
          ? "Initial stock imported from TamizhTech website catalog" 
          : "Opening Stock upon product creation",
        createdById: userId || null,
      },
    });
  }

  return product;
}

/**
 * Records an adjustment, damage, purchase, or return in the Stock Ledger and updates Product stockQuantity atomically.
 * Manual SALE movements are blocked (SALE is strictly generated by billing).
 * Negative stock is blocked.
 */
export async function adjustStock(input: AdjustStockInput) {
  const product = await prisma.product.findUnique({
    where: { id: input.productId },
  });

  if (!product) {
    throw new Error("Product not found");
  }

  if (product.type === "SERVICE") {
    throw new Error("Services do not track physical inventory");
  }

  if (input.type === "SALE" && !input.isBilling) {
    throw new Error("Sales movements can only be generated by issuing bills.");
  }

  const quantitySigned = Number(input.quantityChange);
  if (isNaN(quantitySigned) || quantitySigned === 0) {
    throw new Error("Invalid quantity change");
  }

  const currentStock = product.stockQuantity || 0;
  if (currentStock + quantitySigned < 0) {
    throw new Error(`Insufficient stock: requested ${Math.abs(quantitySigned)} but only ${currentStock} available.`);
  }

  const newStock = currentStock + quantitySigned;

  // Write immutable ledger entry
  const entry = await prisma.stockLedgerEntry.create({
    data: {
      productId: product.id,
      quantitySigned,
      type: input.type,
      referenceType: "MANUAL_ADJUSTMENT",
      notes: input.notes || `Stock ${input.type}`,
      createdById: input.userId || null,
    },
  });

  // Update product stock balance
  const updatedProduct = await prisma.product.update({
    where: { id: product.id },
    data: {
      stockQuantity: newStock,
    },
  });

  return { product: updatedProduct, entry };
}

/**
 * Lock 1 & 4: Deducts stock when a bill is ISSUED or FULFILLED.
 * Only applies to PHYSICAL_PRODUCT items. Services create no stock movement.
 * Draft bills must NEVER invoke this.
 */
export async function deductStockForIssuedInvoice(invoiceId: string, userId?: string) {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      items: {
        include: {
          product: true,
        },
      },
    },
  });

  if (!invoice) {
    throw new Error("Invoice not found");
  }

  // Prevent duplicate deductions if already deducted
  const existingEntries = await prisma.stockLedgerEntry.findMany({
    where: {
      referenceType: "INVOICE",
      referenceId: invoiceId,
      type: "SALE",
    },
  });

  if (existingEntries.length > 0) {
    console.log(`[StockService] Stock already deducted for invoice ${invoiceId}`);
    return;
  }

  const physicalItems = invoice.items.filter(
    (item) => item.productId && item.product && item.product.type === "PHYSICAL_PRODUCT"
  );

  for (const item of physicalItems) {
    if (!item.productId) continue;

    const qtyToDeduct = Math.round(item.qty ?? 1);
    const currentWACPaise = await getProductRollingWACPaise(item.productId);
    const costAmountPaise = safeMultiplyQuantityByPaise(qtyToDeduct, currentWACPaise);

    await prisma.stockLedgerEntry.create({
      data: {
        productId: item.productId,
        quantitySigned: -qtyToDeduct,
        unitCost: currentWACPaise,
        costAmount: costAmountPaise,
        type: "SALE",
        referenceType: "INVOICE",
        referenceId: invoiceId,
        notes: `Sale via Invoice ${invoice.invoiceNo} (${item.description})`,
        createdById: userId || null,
        createdAt: invoice.issuedAt || invoice.date || new Date(),
      },
    });

    // Update product stockQuantity
    await prisma.product.update({
      where: { id: item.productId },
      data: {
        stockQuantity: {
          decrement: qtyToDeduct,
        },
      },
    });
  }
}

/**
 * Reverses stock deductions when an ISSUED invoice is CANCELLED.
 * Restores stock with CUSTOMER_RETURN entries preserving original sale cost.
 */
export async function reverseStockForCancelledInvoice(invoiceId: string, userId?: string) {
  const saleEntries = await prisma.stockLedgerEntry.findMany({
    where: {
      referenceType: "INVOICE",
      referenceId: invoiceId,
      type: "SALE",
    },
  });

  if (saleEntries.length === 0) {
    // Invoice was cancelled while in DRAFT (no stock was ever deducted)
    return;
  }

  // Check if reversal was already performed
  const reversalEntries = await prisma.stockLedgerEntry.findMany({
    where: {
      referenceType: "INVOICE",
      referenceId: invoiceId,
      type: { in: ["RETURN", "CUSTOMER_RETURN"] },
    },
  });

  if (reversalEntries.length > 0) {
    return;
  }

  for (const entry of saleEntries) {
    const qtyToRestore = Math.abs(entry.quantitySigned);

    await prisma.stockLedgerEntry.create({
      data: {
        productId: entry.productId,
        quantitySigned: qtyToRestore,
        unitCost: entry.unitCost,
        costAmount: entry.costAmount,
        type: "CUSTOMER_RETURN",
        referenceType: "INVOICE",
        referenceId: invoiceId,
        notes: `Restored stock from cancelled invoice ${invoiceId}`,
        createdById: userId || null,
      },
    });

    await prisma.product.update({
      where: { id: entry.productId },
      data: {
        stockQuantity: {
          increment: qtyToRestore,
        },
      },
    });
  }
}

/**
 * Returns complete stock movement history for a product.
 */
export async function getProductStockHistory(productId: string) {
  return prisma.stockLedgerEntry.findMany({
    where: { productId },
    include: {
      createdBy: {
        select: { name: true, email: true },
      },
    },
    orderBy: { createdAt: "desc" },
  });
}
